GET /posts HTTP/1.1
Host: localhost:8080

POST /posts HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "id": 3,
    "timestamp": "2024-04-25T19:39:00.269214-05:00",
    "comment": "aqui con mis mascotas",
    "reactions": 0
}
